### ISSUE TITLE
if I want to use BasicDAO ,how can I use?

### ISSUE THREAD

**Issue by yangbo-true** [ganchix/morphia-spring-boot-starter#25]

**Comment by yangbo-true** [comment]
somebody here?

**Comment by yangbo-true** [comment]
?

**Comment by ganchix** [comment]
Hi,

Thanks for your issue, you can take a look to Readme, https://github.com/ganchix/morphia-spring-boot-starter/blob/master/README.md .

Can you be more specific in your question?

**Comment by ganchix** [comment]
Did you solve your problem @yangbo-true ?
